import type { HeroLayerId } from './heroEnvironmentRegistration';

export const HERO_ENVIRONMENT_ASSETS: Record<HeroLayerId, number> = {
  hero_bonsai: require('../../../../assets/hero/environment/layers/hero_bonsai.png'),
  hero_clouds: require('../../../../assets/hero/environment/layers/hero_clouds.png'),
  hero_evening_haze: require('../../../../assets/hero/environment/layers/hero_evening_haze.png'),
  hero_falling_petals: require('../../../../assets/hero/environment/layers/hero_falling_petals.png'),
  hero_far_shoreline: require('../../../../assets/hero/environment/layers/hero_far_shoreline.png'),
  hero_fireflies: require('../../../../assets/hero/environment/layers/hero_fireflies.png'),
  hero_floor: require('../../../../assets/hero/environment/layers/hero_floor.png'),
  hero_fuji: require('../../../../assets/hero/environment/layers/hero_fuji.png'),
  hero_hills: require('../../../../assets/hero/environment/layers/hero_hills.png'),
  hero_inbox_tray_empty: require('../../../../assets/hero/environment/layers/hero_inbox_tray_empty.png'),
  hero_inbox_tray_full: require('../../../../assets/hero/environment/layers/hero_inbox_tray_full.png'),
  hero_inbox_tray_partial: require('../../../../assets/hero/environment/layers/hero_inbox_tray_partial.png'),
  hero_lake: require('../../../../assets/hero/environment/layers/hero_lake.png'),
  hero_lantern: require('../../../../assets/hero/environment/layers/hero_lantern.png'),
  hero_meditation_cushion: require('../../../../assets/hero/environment/layers/hero_meditation_cushion.png'),
  hero_morning_mist: require('../../../../assets/hero/environment/layers/hero_morning_mist.png'),
  hero_moss: require('../../../../assets/hero/environment/layers/hero_moss.png'),
  hero_near_shoreline: require('../../../../assets/hero/environment/layers/hero_near_shoreline.png'),
  hero_pillar: require('../../../../assets/hero/environment/layers/hero_pillar.png'),
  hero_rain: require('../../../../assets/hero/environment/layers/hero_rain.png'),
  hero_rocks: require('../../../../assets/hero/environment/layers/hero_rocks.png'),
  hero_roof: require('../../../../assets/hero/environment/layers/hero_roof.png'),
  hero_scroll: require('../../../../assets/hero/environment/layers/hero_scroll.png'),
  hero_scroll_open: require('../../../../assets/hero/environment/layers/hero_scroll_open.png'),
  hero_snow: require('../../../../assets/hero/environment/layers/hero_snow.png'),
  hero_steps: require('../../../../assets/hero/environment/layers/hero_steps.png'),
  hero_sword_stand: require('../../../../assets/hero/environment/layers/hero_sword_stand.png'),
  hero_training_post: require('../../../../assets/hero/environment/layers/hero_training_post.png'),
  hero_veranda: require('../../../../assets/hero/environment/layers/hero_veranda.png'),
};
